config/routes.rb
Rails.application.routes.draw do
  devise_for :users
root to: 'products#index'
  resources :products do
    post :buy, on: :member
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_product, only: [ :edit, :update, :destroy, :buy]

  # GET /products
  # GET /products.json
  def index
    # @products = Product.all
    @products_fridge = Product.where(bought: true)
    @products_todo = Product.where(bought: false)
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)
    @product.user = current_user
    respond_to do |format|
      if @product.save
        format.html { redirect_to products_path, notice: 'Dodałaś/eś nowy smakołyk do listy zakupów.' }
        # format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to products_path, notice: 'Zmieniłaś/eś smakołyk. Mam nadzieję, że smaczne!' }
        # format.json { render :products_url, status: :ok, location: @product }
      else
        format.html { render :edit }
        # format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    notice = if @product.bought? then
      "Na zdrowie!"
    else
      "No trudno!"
    end

    respond_to do |format|
      format.html { redirect_to products_url, notice: notice }
      format.json { head :no_content }
    end
  end

  # BUY products/1
  def buy
    @product.bought = true
    @product.save
    #@product.update({bought: true})
    redirect_to products_url, notice: 'Kupiłaś/eś! Będzie pysznie!'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fridge</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if user_signed_in? then %>
    <div class="navbar">
      <h1> Witaj
      <%= current_user.email %>
    </h1>
    <%= button_to 'Wyloguj mnie!', destroy_user_session_path, method: :delete, data: { confirm: 'Na pewno chcesz się wylogować?' } %>
    <% end %>
    </div>
    <%= yield %>
  </body>
</html>

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name, "Smakołyk" %>
    <%= form.text_field :name, id: :product_name %>
  </div>

  <div class="actions">
    <%= form.submit "Zapisz smakołyk" %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Zmień smakołyk</h1>

<%= render 'form', product: @product %>

<%= link_to 'Wróc', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>
<div class="my_info">
  <div>
  <h1>Moja Lodówka</h1>
</div>
  <div>
    <div class="fridge-outline">
      <table>
        <tbody>
          <% @products_fridge.each do |product| %>
            <tr>
              <td><%= product.name %></td>
              <td><%= link_to 'Zmień', edit_product_path(product) %></td>
              <td><%= link_to 'Zjedzone!', product, method: :delete, data: { confirm: 'Na pewno zjadłeś/aś?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <div class="fridge-leg left"></div>
      <div class="fridge-leg right"></div>
    </div>
</div>

<div class="my_info">
  <div>
    <h1>Lista zakupów, żarłoku!</h1>
    </div>

    <div class="basic">
      <table>
        <thead>
          <tr>
            <th>Smakołyki</th>
            <th>Zdobywca smakołyku</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @products_todo.each do |product| %>
            <tr>
              <td><%= product.name %></td>
              <td><%= product.user.email %></td>
              <td><%= link_to 'Zmień', edit_product_path(product) %></td>
              <td><%= link_to 'Nie chcę', product, method: :delete, data: { confirm: 'Na pewno nie chcesz?' } %></td>
              <td><%= link_to 'Kupione', buy_product_path(product), method: :post, data: { confirm: 'Na pewno kupiłeś?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>

      <br>
      <%= link_to 'Mam ochotę na coś dobrego', new_product_path %>
      </div>

  </div>

app/views/products/new.html.erb
<h1>Nowy smakołyk</h1>

<%= render 'form', product: @product %>

<%= link_to 'Wróć', products_path %>